services:
  # 1. Discord bot
  discord-bot:
    build: .
    container_name: chihuahua-king-bot
    restart: unless-stopped
    network_mode: host
    env_file:
      - BOT.env
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    volumes:
      - bot-data:/app/data

volumes:
  bot-data:
